// example-angular/src/app/components/news-item/news-item.component.ts
import { Component, Input } from '@angular/core';
import { MONTHS } from 'src/app/constants/MONTHS';
import { INewsItem } from 'src/app/interfaces/INewsItem';

@Component({
  selector: 'news-item',
  templateUrl: './news-item.component.html',
  styleUrls: ['./news-item.component.scss'],
})
export class NewsItemComponent {
  @Input()
  index!: number;

  @Input()
  item!: INewsItem;

  constructor() {}

  getFormattedDate() {
    const parsedDate = new Date(this.item.webPublicationDate);
    return `${parsedDate.getDate()} ${
      MONTHS[parsedDate.getMonth()]
    } ${parsedDate.getFullYear()}`;
  }

}

<div class="rowMiddle newsItem">
    <div class="col">
        <h1>{{ item.webTitle }}</h1>
        <span class="date">{{ getFormattedDate() }}</span>
    </div>
</div>

// example-react/src/components/NewsItem.tsx
import { useMemo } from 'react';
import { MONTHS } from '../constants/MONTHS';
import { INewsItem } from '../types/INewsItem';
import './NewsItem.scss';

export const NewsItem = ({ item }: { item: INewsItem }) => {
	const formatedDate: string = useMemo(() => {
		const parsedDate = new Date(item.webPublicationDate);
		return `${parsedDate.getDate()} ${MONTHS[parsedDate.getMonth()]} ${parsedDate.getFullYear()}`;
	}, [item]);

	return (
		<div className='rowMiddle newsItem'>
			<div className='col'>
				<h1>{item.webTitle}</h1>
				<span className='date'>{formatedDate}</span>
			</div>
		</div>
	);
};
